### ISSUE TITLE
能否设置在只有OPENAI_COMPLETIONS_API的情况下也显示summary按钮

### ISSUE THREAD

**Issue by KEVIN-G386** [TBXark/mail2telegram#11]
由于GPT的API的接口是我自己做的代理，还有从别的网站搞的的api，没有设置api key，这样就显示不出summary按钮，设置了key就会报错，请问这个能解决吗

**Comment by TBXark** [comment]
https://github.com/TBXark/mail2telegram/blob/cbbad44d28bc22f444024963c2ccd9932fd6d2da/src/render.js#L79

你可以fork一份然后修改一下这个的判断，直接改成永远是true就可以了

**Comment by KEVIN-G386** [comment]
谢谢，我试试
