### ISSUE TITLE
Doubt (Sorry For Opening A Issue)

### ISSUE THREAD

**Issue by MrxAravind** [TBXark/mail2telegram#17]
Do I need to have a domain to this to work!?

**Comment by TBXark** [comment]
Cloudflare Workers have a default domain.

**Comment by MrxAravind** [comment]
U mean i should make a example cf worker and get it's url and use in variable,if so than my mail address will like  name@project_name.user_name.workers.dev?

**Comment by TBXark** [comment]
The domain is used for previewing web pages, not for e-mail addresses.

**Comment by TBXark** [comment]
No, I think you misunderstood. For details, please read this blog https://blog.cloudflare.com/introducing-email-routing/
