### ISSUE TITLE
`TELEGRAM_ID` Failed to send when entering group id

### ISSUE THREAD

**Issue by shaonianche** [TBXark/mail2telegram#18]
- Whether the group id needs to be prefixed e.g. -xxxx or xxxx ？
- The email is sent successfully when the individual id is entered, but the email is not delivered when the group id is entered.

**Comment by shaonianche** [comment]
> GROUP's start with -100
There are some questions here, the group id I found for myself doesn't start with 100 ..

**Comment by TBXark** [comment]
Bots in Telegram groups need permission to send messages proactively. The simplest way is to set the bot as an administrator.

**Comment by shaonianche** [comment]
> Bots in Telegram groups need permission to send messages proactively. The simplest way is to set the bot as an administrator.


It has permission to send messages, does it work in your configuration?

**Comment by TBXark** [comment]
Yes

**Comment by shaonianche** [comment]
Thanks to the author for the program, it's fantastic. 
I think I found the reason how to use the group ID if the prefix must be -100
Note: if your group chat id is 12345678 then you need to prefix it with -100 such that it is -10012345678.
