### ISSUE TITLE
Regex Whitelist Fails

### ISSUE THREAD

**Issue by maggyium** [TBXark/mail2telegram#19]
I want to approve all the email coming into the domain ,
i've added the following regex:
`^(([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+([;.](([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+)*$`
& 
`\w*@\w*.\w*`
Neither one is working 
so i tested the one shown in example image
added `\d@gg.co` and trying the test email function it doesn't show up anything when i enter 99@gg.co

![image](https://github.com/user-attachments/assets/90631cf2-a197-434b-92cd-4131755e428f)
![image](https://github.com/user-attachments/assets/669814f2-2ed1-470a-8eda-eac6ffe7fe6e)
Only adding the complete email address seems to work

**Comment by TBXark** [comment]
In fact, you don't need to verify the correctness of the email format, because it is always correct. So when you want to allow all addresses, you can directly use `.*`.

**Comment by TBXark** [comment]
```js
const reg = new RegExp(`^(([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+([;.](([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+)*$`)
console.log(reg.test('99@gg.co'))
```
```

const reg = new RegExp(`^(([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+([;.](([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+)*$`)
            ^

SyntaxError: Invalid regular expression: /^(([a-zA-Z0-9_-.]+)@([a-zA-Z0-9_-.]+).([a-zA-Z]{2,5}){1,25})+([;.](([a-zA-Z0-9_-.]+)@([a-zA-Z0-9_-.]+).([a-zA-Z]{2,5}){1,25})+)*$/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.<anonymous> (/Users/tbxark/Library/Application Support/CodeRunner/Unsaved/Untitled.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:166:5)
    at node:internal/main/run_main_module:30:49
```

**Comment by TBXark** [comment]
<img width="958" alt="image" src="https://github.com/user-attachments/assets/143a1bc7-3d00-4ba7-ad82-5a7e7d885c9e">
It seems to be just a bug in my testing page.

**Comment by maggyium** [comment]
Its not just the test page tho i'm not receiving emails unless i keep the complete address

**Comment by TBXark** [comment]
<img width="555" alt="image" src="https://github.com/user-attachments/assets/36684f03-af8f-4a4a-bef2-0fcf5d467e4e">

It seems that my parameters are written in reverse.

**Comment by maggyium** [comment]
Plus there's another bug , so i have two chat ids one group and another personal, emails do get sent to both but commands only work in personal.

**Comment by TBXark** [comment]
You must `@` the bot in the group for it to take effect.

**Comment by TBXark** [comment]
Oh, it may not work, I haven't specifically adapted it for groups.

**Comment by maggyium** [comment]
> You must `@` the bot in the group for it to take effect.

I tried the command with @ tg auto fills that in group it didnt work, tried replying to bot's msg with command, still didn't work tho

**Comment by TBXark** [comment]
Maybe `/start @botname` will work, the command must be in front.

**Comment by TBXark** [comment]
You can create a separate issue and I will specifically adapt the group command for it.

**Comment by maggyium** [comment]
That aside, so with `.*` regex entry even if test mail fails it should receive the email right ?

**Comment by TBXark** [comment]
1. First, test the whitelist.
2. Then test the blacklist.
3. The rest can be directly allowed.

**Comment by maggyium** [comment]
I am using "https://sendtestemail.com/" to test if i can receive emails or not , its showing status : bounced(few hrs ago i did receive emails from thsi), and i tried the youtube signup email too, i receive it on my another email but not getting it here.

**Comment by TBXark** [comment]
You can check the logs in the Cloudflare backend, and it's best to set up `FORWARD_LIST` for easier testing.

**Comment by maggyium** [comment]
FORWARD_LIST is to fwd the email to another email address for backup am i right ? , is there other process thats needs to be done or i can just add the email to this env var

**Comment by TBXark** [comment]
Need to add the addresses in `FORWARD_LIST` to the trusted list in Cloudflare.

**Comment by maggyium** [comment]
Yeah found the issue while doing that , apparently cloudflare had toggled catch-all off by itself :) now its working

**Comment by maggyium** [comment]
want me to close this or just convert this into the grp commands not working issue ?
