### ISSUE TITLE
E-mails containing files in html mode

### ISSUE THREAD

**Issue by Ermaotie** [TBXark/mail2telegram#2]
When I try to test the file in email is available. and I just put a file in the email. I got nothing.
So could you tell me if the forwarding service supports emails containing files please? Thank you！

**Comment by TBXark** [comment]
Now the Telegram preview does not support file, but the forwarding function supports files. You can add an alternative email address to `FORWARD_LIST` and then download the corresponding file from this email.

**Comment by Ermaotie** [comment]
OK, thanks for your answer!🙇‍

**Comment by TBXark** [comment]
I added the attachment download feature in https://github.com/TBXark/testmail-viewer/commit/9e700ad673933421c4f5ad256911d7cae02f6d35. You can use it in combination with mail2telegram by simply adding testmail to the forwarding address.
