### ISSUE TITLE
Feature: Show mail subject in telegram message

### ISSUE THREAD

**Issue by 0xAWM** [TBXark/mail2telegram#4]
Currently, only the recipient and sender are displayed in the message. It would be better if the subject of the email could be displayed.

Thx for ur work.

**Comment by TBXark** [comment]
It should show the subject, is your bot not showing up properly, can you take a screenshot?

![](https://github.com/TBXark/mail2telegram/blob/master/example.png)

**Comment by 0xAWM** [comment]
I used "test" in both the subject and content of the email.😅 Sorry for bothering.

Propose a more elegant format:

```
$Email Text Content$

______
Subject: $Subject$
From: $From$
To: $To$
```

**Comment by TBXark** [comment]
Email Text Content is sometimes too long for full display, so in the latest version, you can click Preview to display the full Email Text Content in telegram.
