### ISSUE TITLE
Email Dropped

### ISSUE THREAD

**Issue by soldiweb** [TBXark/mail2telegram#6]
Thanks for open-sourcing this, I'm new to Cloudflare workers and TG bot and i've learned a lot from the code.

I deployed via copy and paste and each time I send an email it gets dropped, i've pasted the index.js in the build folder, set up cath-all in the email forwarder via my worker and i've correctly added all vars, but i'm not sure if i have to use my own Telegram ID or the one of the BOT created with Botfather.

Thanks for any guidance you can provide.

**Comment by TBXark** [comment]
<img width="284" alt="image" src="https://github.com/TBXark/mail2telegram/assets/9513891/54fdcf7b-8d05-4d3a-b4c4-355fc74c8749">

If you are referring to the status of this, as long as you have not filled in `FORWARD_LIST`, the result will be Drop because there is no forwarding or rejection.

**Comment by Mrzhuo2022** [comment]
你好，请问我按照要求部署了这个，发送邮箱测试的时候，在kv里面能看到发送的信息，但是并没有转发到tg机器人中，并且信息的状态也是drop，我填了 `FORWARD_LIST`

**Comment by TBXark** [comment]
> 你好，请问我按照要求部署了这个，发送邮箱测试的时候，在kv里面能看到发送的信息，但是并没有转发到tg机器人中，并且信息的状态也是drop，我填了 `FORWARD_LIST`

截图看看你的环境变量的设置，注意裁剪掉value区域

**Comment by Mrzhuo2022** [comment]
> > > 你好，请问我按照要求部署了这个，发送邮箱测试的时候，在kv里面能看到发送的信息，但是并没有转发到tg机器人中，并且信息的状态也是drop，我填了 `FORWARD_LIST`
> > 
> > 
> > 截图看看你的环境变量的设置，注意裁剪掉value区域
> 
> ![Snipaste_2023-11-29_16-52-30](https://private-user-images.githubusercontent.com/98103360/286533631-7d2f69f0-a2e3-4ce1-b5eb-c422027f62a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDgyOTcsIm5iZiI6MTcwMTI0Nzk5NywicGF0aCI6Ii85ODEwMzM2MC8yODY1MzM2MzEtN2QyZjY5ZjAtYTJlMy00Y2UxLWI1ZWItYzQyMjAyN2Y2MmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4NTMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZGJlODZhMmM2ZmE2Mzk4ZDU4ZDFkNmZmZWU4ZWY1ODMzZDE5OTQ3ODE0Y2ZlOWJjOThiZjdlZmNiYjNmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.576QhA8IBlH9jKnGeMS0lpNxFCrotlS2u-QzmNh988A)



> > 你好，请问我按照要求部署了这个，发送邮箱测试的时候，在kv里面能看到发送的信息，但是并没有转发到tg机器人中，并且信息的状态也是drop，我填了 `FORWARD_LIST`
> 
> 截图看看你的环境变量的设置，注意裁剪掉value区域

我刚刚又试了一些，邮件有转发到邮箱，但是在tg机器人中没有消息。

**Comment by TBXark** [comment]
> > > > 你好，请问我按照要求部署了这个，发送邮箱测试的时候，在kv里面能看到发送的信息，但是并没有转发到tg机器人中，并且信息的状态也是drop，我填了 `FORWARD_LIST`
> > > 
> > > 
> > > 截图看看你的环境变量的设置，注意裁剪掉value区域
> > 
> > 
> > ![Snipaste_2023-11-29_16-52-30](https://private-user-images.githubusercontent.com/98103360/286533631-7d2f69f0-a2e3-4ce1-b5eb-c422027f62a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDgyOTcsIm5iZiI6MTcwMTI0Nzk5NywicGF0aCI6Ii85ODEwMzM2MC8yODY1MzM2MzEtN2QyZjY5ZjAtYTJlMy00Y2UxLWI1ZWItYzQyMjAyN2Y2MmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4NTMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZGJlODZhMmM2ZmE2Mzk4ZDU4ZDFkNmZmZWU4ZWY1ODMzZDE5OTQ3ODE0Y2ZlOWJjOThiZjdlZmNiYjNmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.576QhA8IBlH9jKnGeMS0lpNxFCrotlS2u-QzmNh988A)
> 
> > > 你好，请问我按照要求部署了这个，发送邮箱测试的时候，在kv里面能看到发送的信息，但是并没有转发到tg机器人中，并且信息的状态也是drop，我填了 `FORWARD_LIST`
> > 
> > 
> > 截图看看你的环境变量的设置，注意裁剪掉value区域
> 
> 我刚刚又试了一些，邮件有转发到邮箱，但是在tg机器人中没有消息。

id写错了，是一个纯数字，不是id。回头我加一个获取id的指令方便获取id。

**Comment by TBXark** [comment]
@soldiweb 

The forwarded email should be added to "Email Routing - Destination addresses" after authentication in order to receive emails. Instructions will be added to the document later.


被转发的邮箱应该是要在 `Email Routing - Destination addresses` 中添加认证之后才能收到邮件，稍后会在文档中添加说明

**Comment by Mrzhuo2022** [comment]
> @soldiweb
> 
> The forwarded email should be added to "Email Routing - Destination addresses" after authentication in order to receive emails. Instructions will be added to the document later.
> 
> 被转发的邮箱应该是要在 `Email Routing - Destination addresses` 中添加认证之后才能收到邮件，稍后会在文档中添加说明

好的，感谢你的帮助，感谢你的开源项目！

**Comment by TBXark** [comment]
@Mrzhuo2022 已添加 可以使用 `/id` 获取
