### ISSUE TITLE
文本预览按钮无反应

### ISSUE THREAD

**Issue by FlechazoPh** [TBXark/mail2telegram#7]
问题： 投递成功之后_(:З」∠)_内预览按钮没反应，内容也不显示
截图： TG 

<img width="379" alt="image" src="https://github.com/TBXark/mail2telegram/assets/94276146/c2116d6a-ac3c-49f2-9931-8360aa4f4fdc">

邮件：

<img width="290" alt="image" src="https://github.com/TBXark/mail2telegram/assets/94276146/2bf5d690-c474-4e7e-b5b9-fd9094092104">

环境变量配置截图：

<img width="1185" alt="image" src="https://github.com/TBXark/mail2telegram/assets/94276146/fdf7e6fd-8e82-4a04-b4fd-08301efa6cc0">
 
环境变量已经绑定了  域名/init,但是 tg 里没有应用内预览

**Comment by TBXark** [comment]
域名不用加 `/init`。 只用写域名 `xxx.xxx.workers.dev`

**Comment by TBXark** [comment]
还需要绑定 kv_namespaces 名字要设成 DB
<img width="860" alt="image" src="https://github.com/TBXark/mail2telegram/assets/9513891/b89852a5-c7f2-4098-b28a-51045b76d672">

**Comment by TBXark** [comment]
28afcbed98a91e77f069be672ae165ccbab23c6d 新的commit优化了绑定接口的返回值来确定是否绑定成功

**Comment by FlechazoPh** [comment]
我是看的这个  #3   这个issue 加的/init， **想在tg应用内显示邮件内容**。
改回来了还是没有preview，按钮没有反应：
<img width="424" alt="image" src="https://github.com/TBXark/mail2telegram/assets/94276146/34cd1018-cd28-452e-9880-ce7c8734bf5f">


kv_namespaces 之前已经绑定过了：

<img width="900" alt="image" src="https://github.com/TBXark/mail2telegram/assets/94276146/939e9b50-7629-4c47-84fb-3339f1678e19">

**Comment by TBXark** [comment]
改DOMAIN后重新init绑定一下

**Comment by FlechazoPh** [comment]
> 改DOMAIN后重新init绑定一下

现在可以Preview，谢谢大佬。

我想问下有办法直接在TG的对话里显示邮件内容么？这里直接显示内容：
<img width="376" alt="image" src="https://github.com/TBXark/mail2telegram/assets/94276146/0be836d0-88be-448a-8526-961a4262e7ec">

**Comment by TBXark** [comment]
你可以改一下这一个函数的实现去添加内容, 我为了保持列表整洁我就没有加了。
https://github.com/TBXark/mail2telegram/blob/28afcbed98a91e77f069be672ae165ccbab23c6d/index.js#L139-L207
