### ISSUE TITLE
能否设置个简单BLOCK发件人的按钮

### ISSUE THREAD

**Issue by Zding89** [TBXark/mail2telegram#8]
使用场景是用来注册一些网站，有些网站会定期发推销，但如果每次都得弄正则list比较麻烦，要是能在tg上直接点击block会比较好

**Comment by TBXark** [comment]
其实现在是支持使用命令添加 block的，但是我没写到文档里面，也没有添加绑定功能。等我优化一下文档。

**Comment by TBXark** [comment]
<img width="572" alt="image" src="https://github.com/TBXark/mail2telegram/assets/9513891/f3c80983-13c2-4d1a-abfe-465c0a24b46b">
