### ISSUE TITLE
无论作何操作均会失败

### ISSUE THREAD

**Issue by roywangdev** [TBXark/mail2telegram#9]
"logs": [
    {
      "message": [
        "TypeError: Cannot read properties of undefined (reading 'get')"
      ],
      "level": "error",
      "timestamp": 1712775444629
    }

无论是增加或删除列表的指令，还是向TG推送，均失败。

**Comment by roywangdev** [comment]
使用的是项目中编译好的版本。变量仅配置了 DOMAIN、FORWARD_LIST、TELEGRAM_ID、TELEGRAM_TOKEN、WHITE_LIST

**Comment by TBXark** [comment]
你少了这一步吧
- 绑定 `KV Namespace Bindings` 数据库到worker, 名字必须为`DB`
